title:   ANJALI GUJJAR
logo: /assets/images/AnjaliGujjar.JPG
description:
    <li>Information Systems Graduate Specialized in Business Data Analytics and Project Management</li>
    <li>3+ years of experience in Salesforce, Data Analytics, Application Development, and SAP</li>
    <li>Salesforce Certified Administrator</li>
    <li>Lean Six Sigma Green Belt</li>
    <li>Co-Founded a Tech Solutions Company at the age of 19 !</li>
  </ul>
theme: jekyll-theme-minimal


