title:   ANJALI GUJJAR
logo: /assets/images/AnjaliGujjar.JPG
description: Information Systems Graduate  Specialized in Business Data Analytics and Project Management.  Co-Founded a Tech Solutions at the age of 193+ years of experience in Salesforce, Data Analytics, Application Development, and SAP.  Certified Salesforce Administrator and Lean Six Sigma Green Belt.  Passionate about applying technology to solve business challenges and optimize processes.
theme: jekyll-theme-minimal
stylesheet: /assets/css/color.css
