title:   ANJALI GUJJAR
logo: /assets/images/AnjaliGujjar.JPG
description: |
  <strong>Summary:</strong><br>
  Information Systems Graduate Specialized in Business Data Analytics and Project Management.<br>
    <li>3+ years of experience in Salesforce, Data Analytics, Application Development, and SAP</li>
    <li>Salesforce Certified Administrator</li>
    <li>Lean Six Sigma Green Belt</li>
    <li>Co-Founder of a Tech Solutions Company at the age of 19 !</li>
  </ul>
theme: jekyll-theme-minimal
